# netlify.toml 

[build]
  command = "yarn build"
  publish = "dist"
  functions = "lambda"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
<<<<<<< HEAD
    Content-Security-Policy = "base-uri 'none'; default-src 'self' 'unsafe-inline' data: https:; object-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; block-all-mixed-content:; report-uri https://1c2d762fff1f59d8efe7f471bcc6fcbe.report-uri.com/r/d/csp/enforce;"
=======
    Content-Security-Policy = "base-uri 'none'; default-src 'self' 'unsafe-inline' data: https:; object-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; block-all-mixed-content:; report-uri https://1c2d762fff1f59d8efe7f471bcc6fcbe.report-uri.com/r/d/csp/enforce;"
>>>>>>> 4c3ce17a5eca7d73a4b714b5992afa554367720f
    X-Content-Type-Options = "nosniff"
