# netlify.toml 

[build]
  command = "yarn build"
  publish = "dist"
  functions = "lambda"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"